---
title: "FV-Raw-Spirit-Data-Wrangle"
author: "Tim van der Stap"
date: "2023-07-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(readxl)
library(here)
library(lubridate)
library(obistools)

```

When downloading the file from the GitHub repo, make sure that you select the correct version.

```{r data download, include=FALSE}
download.file("https://github.com/international-year-of-the-salmon/2022-raw-spirit-data-template/blob/main/original_data/IYS2022_Data_template_RS.xlsx", here::here("IYS_data_template", "IYS2022_Data_template_RS.xlsx"), quiet = TRUE, mode = "wb")

```

Create function to determine polygon coordinates required for the metadata:

```{r polygon coordinates, include = FALSE}

polygon_coords <- function(event){
  event <- event %>% select(latitude_start_decdeg, longitude_start_decdeg) %>% 
    drop_na(latitude_start_decdeg, longitude_start_decdeg) 
  ch <- chull(event)
  coords <- event[c(ch, ch[1]), ]
  coords <- paste(coords$latitude_start_decdeg, coords$longitude_start_decdeg, sep = ",", collapse = " ")
  coords
}

```

Create Event Core:

```{r event, include = FALSE}

event <- read_excel(here::here("IYS_data_template", "IYS2022_Data_template_RS.xlsx"), sheet = "4. SAMPLING EVENT INFO")

# Get the polygon coordinates that are useful for the metadata record:
polygon_coords(event)

event <- event %>% filter(event_type == "Trawl") %>%
  mutate(eventDate = paste0(as_date(
    paste0(year, "-", month, "-", day))))

# Confirm event dates are all in order:
obistools::check_eventdate(event)

RS_event <- event %>%
  select(eventID = station_event_ID,
         eventDate,
         year, month, day,
         decimalLatitude = latitude_start_decdeg,
         decimalLongitude = longitude_start_decdeg) %>%
  mutate(minimumDepthInMeters = 0,
         maximumDepthInMeters = 8) %>%
  distinct(eventID, .keep_all = TRUE) %>%
  mutate(geodeticDatum = "WGS84",
         datasetID = " ",
         bibliographicCitation = " ",
         language = "en",
         modified = lubridate::today(),
         license = "https://creativecommons.org/licenses/by/4.0/legalcode")

# Save locally:
write_csv(RS_event, here("standardized_data", "RS2022_event.csv"))
```

Next, create the occurrence extension:

```{r}
occurrence <- read_excel(here::here("IYS_data_template", "IYS2022_Data_template_RS.xlsx"), sheet = "5. CATCH FINAL INFO")

occurrence <- occurrence %>%
  dplyr::rename(occurrenceID = catch_ID,
         verbatimIdentification = species_recorded,
         scientificName = scientific_name) %>%
  select(-taxonomic_rank)

# Confirm that the total catches across species matches the values reported in the paper.
occurrence %>% group_by(scientificName) %>%
    summarise(total_catch = sum(catch_count))

# Get unique species names:
unique_spp <- unique(occurrence$scientificName) %>% as.data.frame()
colnames(unique_spp) <- "scientificName"

unique_spp$specificEpithet <- ""
unique_spp$scientificNameID <- ""
unique_spp$kingdom <- ""
unique_spp$phylum <- ""
unique_spp$class <- ""
unique_spp$order <- ""
unique_spp$family <- ""
unique_spp$genus <- ""
unique_spp$scientificNameAuthorship <- ""
unique_spp$taxonRank <- ""
unique_spp$taxonomicStatus <- ""

# use this loop to populate the unique_spp dataframe:
getid <- function(x) {
  for (i in 1:nrow(x)) 
    if (!is.na(x[i,ncol(x)])){
      if (nchar(x[i,ncol(x)]) == 0) {
        df <- as.data.frame(worrms::wm_records_names(x[i,]$scientificName, fuzzy = TRUE, marine_only = FALSE))
        if (nrow(df) < 1) {
          unique_spp[i,]$scientificNameID <<- NA
        }
        else if (nrow(df) > 1 & df[1,]$status != "accepted") {
          View(df)
          wormsdf <- readline(prompt = "Enter row number:")
          unique_spp[i,]$specificEpithet <<- stringr::word(df[wormsdf,]$scientificname, 2)
          unique_spp[i,]$scientificNameID <<- df[wormsdf,]$lsid
          unique_spp[i,]$kingdom <<- df[wormsdf,]$kingdom
          unique_spp[i,]$phylum <<- df[wormsdf,]$phylum
          unique_spp[i,]$class <<- df[wormsdf,]$class
          unique_spp[i,]$order <<- df[wormsdf,]$order
          unique_spp[i,]$family <<- df[wormsdf,]$family
          unique_spp[i,]$genus <<- df[wormsdf,]$genus
          unique_spp[i,]$scientificNameAuthorship <<- df[wormsdf,]$authority
          unique_spp[i,]$taxonRank <<- df[wormsdf,]$rank
          unique_spp[i,]$taxonomicStatus <<- df[wormsdf,]$status
        }
        else {
          unique_spp[i,]$specificEpithet <<- stringr::word(df[wormsdf,]$scientificname, 2)[1]
          unique_spp[i,]$scientificNameID <<- df$lsid[1]
          unique_spp[i,]$kingdom <<- df$kingdom[1]
          unique_spp[i,]$phylum <<- df$phylum[1]
          unique_spp[i,]$class <<- df$class[1]
          unique_spp[i,]$order <<- df$order[1]
          unique_spp[i,]$family <<- df$family[1]
          unique_spp[i,]$genus <<- df$genus[1]
          unique_spp[i,]$scientificNameAuthorship <<- df$authority[1]
          unique_spp[i,]$taxonRank <<- df$rank[1]
          unique_spp[i,]$taxonomicStatus <<- df$status[1]
          message(paste("Looking up information for species:", x[i,]$scientificName))
        }
      }
    }
}
getid(unique_spp)
print(unique_spp)

rs_occurrence <- left_join(occurrence, unique_spp, by = "scientificName")
  
  # Omit biomass data from the occurrence extension:
rs_occurrence <- rs_occurrence %>%
    select(eventID = station_event_ID,
           occurrenceID,
           scientificName,
           verbatimIdentification,
           scientificNameID,
           scientificNameAuthorship,
           taxonomicStatus,
           taxonRank, 
           individualCount = catch_count, kingdom, phylum, 
           class, order, family, genus, specificEpithet) %>% 
    distinct() %>%
    mutate(basisOfRecord = "HumanObservation",
           occurrenceStatus = "present")
  
# Save locally:
write_csv(rs_occurrence, here("standardized_data", "RS2022_occurrence.csv"))

```

Finally, create an eMOF extension for the water temperatures associated with the catches.

```{r emof}

rs_temp <- read_excel(here::here("IYS_data_template", "IYS2022_Data_template_RS.xlsx"), sheet = "8. CTD INFO")

# Replace CTD in the station_event_ID with Trawl so that it becomes nested under the correct eventID:
rs_temp$station_event_ID <- gsub("CTD", "Trawl", rs_temp$station_event_ID)

rs_temp <- rs_temp %>%
  select(eventID = station_event_ID,
         sampling_depth_meters,
         sea_water_temperature) %>%
  na.omit()

rs_temp <- rs_temp %>%
  mutate(sea_surface_temperature = ifelse(sampling_depth_meters == 0, sea_water_temperature, NA),
         sea_water_temperature_1m = ifelse(sampling_depth_meters == 1, sea_water_temperature, NA))

rs_temp <- rs_temp %>%
  select(eventID, sea_surface_temperature, sea_water_temperature_1m) %>%
  mutate_all(as.character) %>%
  pivot_longer(cols = c(sea_surface_temperature:sea_water_temperature_1m),
               names_to = "measurementType",
               values_to = "measurementValue") %>%
  na.omit() %>%
  mutate(measurementID = paste(eventID, measurementType, sep = "-"),
         measurementTypeID = case_when(
           measurementType == "sea_surface_temperature" ~ "http://vocab.nerc.ac.uk/collection/P07/current/CFSN0381/",
           measurementType == "sea_water_temperature_1m" ~ "http://vocab.nerc.ac.uk/collection/P01/current/TEMPST01/"),
         measurementUnit = "degrees celsius",
         measurementUnitID = "https://vocab.nerc.ac.uk/collection/P06/current/UPAA/",
         measurementValueID = NA) %>%
  select(eventID, measurementID, measurementType, measurementTypeID, measurementValue, measurementValueID,
         measurementUnit, measurementUnitID)

#TODO: Add information from CTD / Vessel if we have more detailed information.
# Data table for the overall catch:

# Save locally:
write_csv(rs_temp, here("standardized_data", "RS2022_emof.csv"))

```


